### ISSUE TITLE
Joining casual random battleground ingroup finder causes error

### ISSUE THREAD

**Issue by ceylina** [lynxium/Broker_StartMenu#1] opened 2015-10-07 11:37 UTC
[ADDON_ACTION_FORBIDDEN] AddOn 'Broker_StartMenu' tried to call the protected function 'JoinBattlefield()'.
[C]: in function `JoinBattlefield'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:524: in function `HonorFrame_Queue'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil

This happens after opening the group finder using broker startmenu then selecting pvp and attempting to join a random casual battleground.

**Comment by lynxium** [comment] 2015-10-07 12:39
I'll look into it!

Thanks for reporting.

**Comment by lynxium** [comment] 2015-10-07 18:49
A friend told me he fixed it! so it's odd that you're still getting this error unless you're using an old version. 

If you have the latest version please post the exact steps so I can reproduce it and hopefully fix it so I'm closing it for now because I cannot reproduce it on the latest version, feel free to open it again.


this issue and I can delve farther and see what's going on but for that you need to provide the exact steps so I can reproduce it.

Like I said in my previous post I'd love to know the exact version you're using, I'm closing it for now, feel free to open it again,

**Closed by lynxium** 2015-10-07 18:49 UTC
Labels: Checking, Potential Third-Party UI Issue, Taint

**Comment by ceylina** [comment] 2015-10-07 23:15
I'm using r20151004002335

But... Can't reproduce it either so maybe it was because it was early in the morning and I was clicking all sorts of things and who knows?

Go ahead and leave this closed/remove it as I was messing with GetLFGQueueStats making an addon for myself and most likely had the loop searching the wrong lfg id/venturing into pvp territory

My bad :O

**Comment by lynxium** [comment] 2015-10-08 04:45
It's okay! ;)
